apiVersion: apps/v1
kind: Deployment
metadata:
  name: php73
spec:
  selector:
    matchLabels:
      app: php73
  replicas: 1
  template:
    metadata:
      labels:
        app: php73
    spec:
      containers:
      - name: php73
        image: php:7.3-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: web-data
          mountPath: /var/www/html
        - name: php73-config
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: web-data-pvc
      - name: php73-config
        configMap:
          name: php73-config
---
apiVersion: v1
kind: Service
metadata:
  name: php73
spec:
  ports:
  - port: 9000
  selector:
    app: php73
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php73-config
data:
  php.ini: |
    memory_limit = 256M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 300
